name: Build
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    name: Build and Test 
    runs-on: ubuntu-latest
    timeout-minutes: 60

    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true

    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache Maven local repository
        uses: actions/cache@v1.1.0
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      - name: Update maven dependencies
        # see https://github.com/qaware/go-offline-maven-plugin
        run: mvn de.qaware.maven:go-offline-maven-plugin:resolve-dependencies --no-transfer-progress

      - name: First build without tests
        run: mvn clean install -DskipTests

      - name: Set docker tag to used for integration tests
        run: echo ::set-env name=TAG::ci

      - name: Start up support Docker containers
        # launch docker composition of supporting services to be reused among module builds. mvn must be run with the github profile.
        run: |
          docker-compose -f docker-compose-it.yml up -d --no-build
         
      - name: Run tests
        #The ci profile awaits for necessary docker containers to be ready, but does not start or stop them, so they're reused across module builds
        run: mvn clean install -Dgeoserver_api_url=http://localhost:18080/geoserver/rest

      - name: Tear down support Docker containers
        run: docker-compose -f docker-compose-it.yml down

      - name: Remove snapshot artifacts from maven cache
        run: for i in $(find ~/.m2/repository -type d -name *-SNAPSHOT);do echo purging $i && rm -rf $i;done
